---
- name: Directory for static HTML Git repositories
  become: yes
  become_user: "{{ deploy_user }}"
  file:
    path: "{{ deploy_user_path }}/checkouts"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
    mode: 0755

- name: Clone or update static HTML Git repositories
  become: yes
  become_user: "{{ deploy_user }}"
  with_items: "{{ static_html_repos }}"
  git:
    repo: "{{ item.git_url }}"
    dest: "{{ item.destination }}"
    accept_hostkey: yes
    clone: yes
    update: yes

- name: NGinX config for static HTML hosts
  become: yes
  become_user: "root"
  with_items: "{{ static_html_repos }}"
  template:
    src: "nginx-static-html-host.j2"
    dest: "/etc/nginx/sites-available/{{ item.name }}_static_html.conf"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_group }}"
